import { createGlobalThemeContract } from '@vanilla-extract/css';

export const themeColorContract = createGlobalThemeContract({
  logoMainblue: 'color-logo-main-blue',
  logoSublime: 'color-logo-sublime',
  secondaryBlue: 'color-secondary-blue',
  secondaryNavyblue: 'color-secondary-navy-blue',
  secondaryNavy: 'color-secondary-navy',
  secondaryGreen: 'color-secondary-green',
  accentYellow: 'color-accent-yellow',
  accentNegativered: 'color-accent-negative-red',
  accentRed: 'color-accent-red',
  accentOrange: 'color-accent-orange',
  grayscaleGray900: 'color-grayscale-gray-900',
  grayscaleGray800: 'color-grayscale-gray-800',
  grayscaleGray700: 'color-grayscale-gray-700',
  grayscaleGray500: 'color-grayscale-gray-500',
  grayscaleGray400: 'color-grayscale-gray-400',
  grayscaleGray300: 'color-grayscale-gray-300',
  grayscaleGray200: 'color-grayscale-gray-200',
  grayscaleGray100: 'color-grayscale-gray-100',
  grayscaleGray50: 'color-grayscale-gray-50',
  white: 'color-white',
  black: 'color-black',
  bluegray: 'color-bluegray',
  disable: 'color-disable',
  bluescaleBlue900: 'color-bluescale-blue-900',
  bluescaleBlue700: 'color-bluescale-blue-700',
  bluescaleBlue600: 'color-bluescale-blue-600',
  bluescaleBlue300: 'color-bluescale-blue-300',
  bluescaleBlue200: 'color-bluescale-blue-200',
  bluescaleBlue100: 'color-bluescale-blue-100',
  bluescaleBlue50: 'color-bluescale-blue-50',
  contentsbg: 'color-contents-bg',
  primary: 'color-primary',
});
